apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp-container
          image: busybox
          command: ["/bin/sh", "-c"]
          args: ["echo USER=$USERNAME && echo PASS=$PASSWORD && sleep 3600"]
          env:
            - name: USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: username
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: password
