---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysecret
  namespace: default
spec:
  encryptedData:
    password: AgALnZ1WnWDDJTuUmG1pyPSZofRLnOb+hXEdpW52Xjfmk0Xl83I4voM/UTSXI6qqBA/yw44VGy/KprrovVp7OrwI9ljctprZ5xU5MP26atee3PDiD9c4u5iNXcRTPdc5ww8dQBk3D8X1biVvlmNfxcw9O+AvNbmYvlB//cHLxPD2BP5yVSKbqRa1DEsIL8kW5rzqPIRPplJoIcQPQ+2QKZuIfftNdBF+XbxX3CPeRLKRJ1ya4outHeTWVNL3x3O8iBpus4SrGD1we24DP0AR53ymHFS0+KV9CCerE3jZo2dGXANOVz1EPGWHzTzPRTt5P16T/Nhl7eDFqIgJWj1wNSeljJYREGSgom2twD/MCCXNZPTvMvCef39ZSjM4Dzbeqo2a5ka9Xpdrs88gQLoU5pNqsgwQJh9xHrf0XLxFne8/2LUVKkgK3FrALep1E3UG8D2fCaOSxvN8ItiN4hBppojxcfdNPKZ5NiUrSJRya0zhnyxdKHhdDm0gJUBJEENPaWUhmGxwyUetJtsZ7Mwh/ohnKBn9oiXwkabr2YgRT/zWyq6PmDUwcdCz8jPDOJ4NVqL2YmU/ua+Pc6IK5oA1zCBywLbwWbHiWl66fk1w49IcoSGTMTZzOlCo1cyrWT2VNaWpw/1dGy/0I+g8LBcxwveGFV/Th5CYaPkBHIfNLuyz6oIGUrd0f5RrcqTvRvxSB8mcvCY2OnbGWJ0=
    username: AgAKpSJYC1VnE5igH7pHv6MEeirGhaozDIcvHm8QbqK41/E5QKv2wNM8upHqnR17w55ROIuA2rrqz7Eym24bc3cu/Pm1sQwi13HwFwTXBOOnnGgf5WWua6xLt1LZhIpfRSFq43A+LI0dGQN4ybvS7D8sqr8UQEj990O8jzK3sLnqcptL5UzkOiHXm+8oCiPuu6Knb91iqvCUnl5DRBuiSwcVE4UOZ4fwxVRAQJxFMDMX0s6PL4Ki6Lg93Z8b2jLc3klZmZTdwy1CQN+fW64QoSNuFg3E+NTFhy6iJmuH3lcHRwMPCWR2hN2wMiHWRbTcUfokEL5+klMGCze/3/QQbZKmkpWCnKB96qpn1bqUedQPg5Q+12DrxOvlRtuRZZe5c9P68v51ACiyWYYxniKoqn26A19ftZl8tDOb4lMwqO/fNJ9OZSwcukhCXetNL62LKnHYWOU5wRmuMLVajMBc9IO5bmQoxYH/H4PKxM75DspDNQIEjkuxQ4rbYw9bBypRDtwCyjDJ0b8FkdkUuqKxXvf5MJNBDoykqUZ2mlXQo2hqJIYPwEQRw/+huKvmujaTRJJosPtnRkCQ/F6RDFV3og4cYsP33aPoTcii9yb/z8MVB78riRzvqxB/MnqTNDJ6JVk7y7QmGrUtC3lwNRZRGjVKPaIvCyFiS495tvGyhDz/ZhRgBt0e37+/RDRgSA4dytcevEb0ow==
  template:
    metadata:
      creationTimestamp: null
      name: mysecret
      namespace: default
